sins = {
    "Death" :
        [
        "Death",
        "dead", 
        "Deceased",
        "Expires",
        "Passed",
        "Coded",
        "Died",
        "Demise",
        "Arrested",
        "Fatality",
        "Succumbed",
        "Unresponsive",
        "DOA",
        "Abortion",
        ],
    "Birth" :
        [
            'Birth', 
            'Delivery',
            'delivered',
            'Infant',
            'Newborn',
            'Neonatal',
            'fetal',
            'NICU',
            'Apgars', #(0-5)
            'Cesarean',
            'Shoulder dystocia',
            'Pregnancy',
            'Uterus',
            'Uterine rupture',
            'Ectopic',
            'Spontaneous',
            'Stillbirth',
            'Fallopian tube',
            'Maternal',
            'Cerebral palsy – CP',
            'Cephalohematoma',
            'Erb’s palsy',
            'Brachial plexus',
            'Merconium ',
            'Kernicterus',
            'Bilirubin',
            'Placental abruption',
            'Reproductive',
            'Hysterectomy',
            'Eclampsia',
            'Infertility',
            'Impotence',
            'Sterility',
            'Oophorectomy',
            'Ovarian'
            'ovary'
            'ovaries',
            'Castration',
            'Testicle',
            'Erectile dysfunction',
            'vasectomy'
        ],
    "Brain" :
        [
            "Brain",
            "head",
            "brainstem",
            "Encephalopathy ",
            "HIE – hypoxic-ischemic encephalopathy",
            "Hypoxia/hypoxic",
            "Anoxic",
            "TBI – traumatic brain injury",
            "CTE – chronic traumatic encephalopathy",
            "Hematoma",
            "Intracranial hemorrhage",
            "Cognitive",
            "Memory loss",
        ],
    "Neurological":
        [
            "Paralysis",
            "paralyzed",
            "Paraplegia",
            "Quadriplegia",
            "Loss of movement",
            "Locked-in syndrome",
            "pseudocoma",
            "Cauda equina syndrome",
            "Amputation",
            "AKA",
            "above the knee",
            "BKA",
            "below the knee",
            "prosthetic",
            "Neurological",
            "Spinal",
            "Spine",
            "Stroke",
            "Seizure",
            "Neurological",
            "Coma",
            "Vegetative",
            "CVA",
            "cerebrovascular accident",
            "Hemorrhage",
            "Neck",
            "SCI",
            "spinal cord injury",
            "Non-functioning arm",
            "Non-functioning leg",
            "Loss of motor function",
        ],
    "Other Deadly":
        [
            "Suicide",
            "Burn",
            "Scalded",
            "Skin graft",
            "thermal",
            "Disfigurement",
            "disfiguring",
            "deformity",
            "Scarring",
            "scar",
            "Reconstructive",
            "Plastic surgery",
            "Vision",
            "Sight",
            "Blindness",
            "Eye",
            "eyes",
            "Optical nerve damage",
            "Hearing",
            "Deaf",
            "deafness",
            "Ear",
            "Organ failure",
            "Organ damage",
            "Internal",
            "Failure"
            "Kidney damage",
            "liver damage",
            "PE",
            "Embolism",
            "Hemorrhage",
            "hemorrhagic",
            "deficit",
            "Sepsis",
            "Aortic Dissection",
            "Ischemic",
            "Slurred speech",
            "Facial droop",
        ],
    "Batch/Class Actions":
        [
            "Batch",
            # "Related ",
            # "Multiple",
            # "Various",
            "Class Action",
            # "Class",
        ],
    "Fracture":
        [
            "Fracture",
            "Compound",
            "Dislocation",
            "Decollation",
            "Decapitation",
        ],
    "Anesthesia/resuscitation":
        [
            "Anesthesia",
            "Resuscitation",
            "Asphyxia",
            "Aspiration",
            "Intubation",
            "Airway",
            "Obstruction",
            "obstructed",
            "Oxygen",
            "Oxygen deprivation",
        ],
    "General terms indicating potential severity":
        [
            "Catastrophic",
            "Severe",
            "Significant",
            "Extensive",
            "Trauma",
            "traumatic",
            "Permanent",
            "Damaged",
            "Impaired",
            "impairment",
            "Failure",
            "Punitive",
            "Exemplary",
            "Treble",
            "Extra-contractual",
        ],
    "Abuse":
        [
            "Sexual",
            "Abuse",
            "Assault",
            "Touching",
            "Inappropriate",
            "contact",
            "Pornography",
            "Video",
            "Photo)",
            "Molestation",
            "Misconduct",
            "Harassment",
            "Rape",
            "Violated",
            "Unnecessary exam",
        ],
    "Long Term Care":
        [
            "Decubitus ulcers",
            "Pressure ulcers",
            "Bed sores",
            "Elopement",
            "Falls",
        ],
        
}
